apiVersion: v1
entries:
  kube-reaper:
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2023-11-06T14:36:51.301439+13:00"
    description: Clean up (delete) Kubernetes namespace resources after a configured
      TTL (time to live)
    digest: b7d56bbc1e9c3471dd15673553998b58199d12bb42d92faf7666fcf166984d97
    home: https://github.com/ahilmathew/kube-reaper
    name: kube-reaper
    sources:
    - https://github.com/ahilmathew/kube-reaper
    urls:
    - kube-reaper-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-11-06T14:36:51.301065+13:00"
    description: Clean up (delete) Kubernetes namespace resources after a configured
      TTL (time to live)
    digest: 753a4d567a3583bc7a193cd2e15701020703858353709dda56ad7759acbd087c
    home: https://github.com/ahilmathew/kube-reaper
    name: kube-reaper
    sources:
    - https://github.com/ahilmathew/kube-reaper
    urls:
    - kube-reaper-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2023-11-06T14:36:51.297347+13:00"
    description: Clean up (delete) Kubernetes namespace resources after a configured
      TTL (time to live)
    digest: ee0468f665235e6ab609e0762414b23950c5ee7c1234355916db66c3f7207443
    home: https://github.com/ahilmathew/kube-reaper
    name: kube-reaper
    sources:
    - https://github.com/ahilmathew/kube-reaper
    urls:
    - kube-reaper-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2023-11-06T14:36:51.295211+13:00"
    description: Clean up (delete) Kubernetes namespace resources after a configured
      TTL (time to live)
    digest: 9235efddc367244b93a0e9eaaba966efb38dd400a5812f8537e17b19d468f65a
    home: https://github.com/ahilmathew/kube-reaper
    name: kube-reaper
    sources:
    - https://github.com/ahilmathew/kube-reaper
    urls:
    - kube-reaper-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2023-11-06T14:36:51.294395+13:00"
    description: Clean up (delete) Kubernetes namespace resources after a configured
      TTL (time to live)
    digest: a9c48e36a286d62f04dfd8b8ae535027c5568db830b7b5f5bdae4289a116970d
    home: https://github.com/ahilmathew/kube-reaper
    name: kube-reaper
    sources:
    - https://github.com/ahilmathew/kube-reaper
    urls:
    - kube-reaper-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2023-11-06T14:36:51.293786+13:00"
    description: Clean up (delete) Kubernetes namespace resources after a configured
      TTL (time to live)
    digest: 80554dbb91ecddfb20c8877bb2812199ca3102baeb48a0a724a5a920319ff78e
    home: https://github.com/ahilmathew/kube-reaper
    name: kube-reaper
    sources:
    - https://github.com/ahilmathew/kube-reaper
    urls:
    - kube-reaper-0.0.1.tgz
    version: 0.0.1
generated: "2023-11-06T14:36:51.293108+13:00"
