kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "janitor.fullname" . }}
  labels:
    app: {{ template "janitor.name" . }}
    chart: {{ template "janitor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "janitor.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "janitor.name" . }}
  namespace: {{ .Release.Namespace }}
