apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "reaper.name" . }}
  labels:
    app: {{ template "reaper.name" . }}
    chart: {{ template "reaper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
