kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "janitor.name" . }}
  labels:
    app: {{ template "janitor.name" . }}
    chart: {{ template "janitor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list", "delete"]